name: plantpedia
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  async_redux: ^2.4.4
  http: ^0.12.0+4
  equatable: ^1.0.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/tropical-leaves.jpg
    - assets/images/placeholder.jpg

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
